name: CI

on:
  push:
    branches:
      - main # Substitua 'main' pelo nome da sua branch principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.6

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false  # Desativa a criação automática de venv por Poetry

      - name: Install dependencies
        run: |
          cd ci_cd_puc/src
          poetry install --no-root  # Instala as dependências sem criar um ambiente virtual

      - name: Run tests
        run: |
          cd ci_cd_puc/src
          poetry run python -m unittest discover  # Substitua pelo comando de teste apropriado

      - name: Build and deploy to PyPI
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          cd ci_cd_puc/src
          poetry build
          poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}  # Configura o token do PyPI
          poetry publish --build
